### ISSUE TITLE
http running at https://127.0.0.1:8888 连接失败 ER_ACCESS_DENIED_ERROR: Access denied for user 'root'@'localhost' (using password: YES)

### ISSUE THREAD

**Issue by dong-lufei** [OblivionTime/chat#7]
我的命令行和navicat 都可以连上我本地mysql ，跑你这代码咋不行。

```

mysql> select host,user,plugin,authentication_string from mysql.user;
+-----------+------------------+-----------------------+------------------------------------------------------------------------+
| host      | user             | plugin                | authentication_string                                                  |
+-----------+------------------+-----------------------+------------------------------------------------------------------------+
| %         | root             | mysql_native_password | *81F5E21E35407D884A6CD4A731AEBFB6AF209E1B                              |
```

**Comment by OblivionTime** [comment]
你mysql的版本是多少,chat数据库试着设置为utf8mb4

**Comment by dong-lufei** [comment]
```
mysql> select version();
+-----------+
| version() |
+-----------+
| 8.0.32    |
+-----------+
1 row in set (0.00 sec)
```
```

$ node -v
v18.16.0
```
```
mysql> use chat;
Database changed
mysql> show variables like 'character\_set\_%';
+--------------------------+---------+
| Variable_name            | Value   |
+--------------------------+---------+
| character_set_client     | gbk     |
| character_set_connection | gbk     |
| character_set_database   | utf8mb4 |
| character_set_filesystem | binary  |
| character_set_results    | gbk     |
| character_set_server     | utf8mb4 |
| character_set_system     | utf8mb3 |
+--------------------------+---------+
7 rows in set, 1 warning (0.00 sec)
```

**Comment by dong-lufei** [comment]
我找到原因了，是密码不对（密码不对，提示访问拒绝太不友好了，一点不精确，不知道写MySQL的人咋想的）。
我本地设置的账号密码都是root（你的密码是123456）。只改了你的db/db.js里的密码，没有改config.json文件里的密码

**Comment by dong-lufei** [comment]
不知道安装依赖报的错，后面会有影响不
```
$ yarn
yarn install v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
[1/4] ⠐ cpu-features
[2/4] ⠐ node-pty
[3/4] ⠐ better-sqlite3
error E:\test\chat\server\node_modules\node-pty: Command failed.
Exit code: 1
Command: node scripts/install.js
Arguments:
Directory: E:\test\chat\server\node_modules\node-pty
Output:
E:\test\chat\server\node_modules\node-pty>if not defined npm_config_node_gyp (node "D:\scoop_user_apps\apps\nodejs18\current\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "D:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
node:internal/modules/cjs/loader:1078
  throw err;
  ^

Error: Cannot find module 'D:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
    at Module._load (node:internal/modules/cjs/loader:920:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}



warning Error running install script for optional dependency: "E:\\test\\chat\\server\\node_modules\\cpu-features: Command failed.
Exit code: 1
Command: node buildcheck.js > buildcheck.gypi && node-gyp rebuild
Arguments:
Directory: E:\\test\\chat\\server\\node_modules\\cpu-features
Output:
E:\\test\\chat\\server\\node_modules\\buildcheck\\lib\\index.js:133
        throw new Error('Unable to detect compiler type');
        ^

Error: Unable to detect compiler type
    at new BuildEnvironment (E:\\test\\chat\\server\\node_modules\\buildcheck\\lib\\index.js:133:15)
    at Object.<anonymous> (E:\\test\\chat\\server\\node_modules\\cpu-features\\buildcheck.js:5:12)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47

Node.js v18.16.0"
info This module is OPTIONAL, you can safely ignore this error
```

**Comment by OblivionTime** [comment]
不影响



| |
***@***.***
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年04月17日 21:41 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [OblivionTime/chat] http running at https://127.0.0.1:8888 连接失败 ER_ACCESS_DENIED_ERROR: Access denied for user 'root'@'localhost' (using password: YES) (Issue #7) |

不知道安装依赖报的错，后面会有影响不

$ yarn
yarn install v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
[1/4] ⠐ cpu-features
[2/4] ⠐ node-pty
[3/4] ⠐ better-sqlite3
error E:\test\chat\server\node_modules\node-pty: Command failed.
Exit code: 1
Command: node scripts/install.js
Arguments:
Directory: E:\test\chat\server\node_modules\node-pty
Output:
E:\test\chat\server\node_modules\node-pty>if not defined npm_config_node_gyp (node "D:\scoop_user_apps\apps\nodejs18\current\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "D:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
node:internal/modules/cjs/loader:1078
  throw err;
  ^

Error: Cannot find module 'D:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
    at Module._load (node:internal/modules/cjs/loader:920:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}



warning Error running install script for optional dependency: "E:\\test\\chat\\server\\node_modules\\cpu-features: Command failed.
Exit code: 1
Command: node buildcheck.js > buildcheck.gypi && node-gyp rebuild
Arguments:
Directory: E:\\test\\chat\\server\\node_modules\\cpu-features
Output:
E:\\test\\chat\\server\\node_modules\\buildcheck\\lib\\index.js:133
        throw new Error('Unable to detect compiler type');
        ^

Error: Unable to detect compiler type
    at new BuildEnvironment (E:\\test\\chat\\server\\node_modules\\buildcheck\\lib\\index.js:133:15)
    at Object.<anonymous> (E:\\test\\chat\\server\\node_modules\\cpu-features\\buildcheck.js:5:12)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47

Node.js v18.16.0"
info This module is OPTIONAL, you can safely ignore this error
